/** Nombres de selecciones en español (UI PRODEMUNDIAL). */
const BY_FIFA: Record<string, string> = {
  ALG: 'Argelia',
  ARG: 'Argentina',
  AUS: 'Australia',
  AUT: 'Austria',
  BEL: 'Bélgica',
  BIH: 'Bosnia y Herzegovina',
  BOL: 'Bolivia',
  BRA: 'Brasil',
  CAN: 'Canadá',
  CHI: 'Chile',
  CIV: 'Costa de Marfil',
  CMR: 'Camerún',
  COD: 'Congo DR',
  COL: 'Colombia',
  CRC: 'Costa Rica',
  CRO: 'Croacia',
  CPV: 'Cabo Verde',
  CUW: 'Curazao',
  CZE: 'Chequia',
  DEN: 'Dinamarca',
  ECU: 'Ecuador',
  EGY: 'Egipto',
  ENG: 'Inglaterra',
  ESP: 'España',
  FRA: 'Francia',
  GER: 'Alemania',
  GHA: 'Ghana',
  GRE: 'Grecia',
  HAI: 'Haití',
  HON: 'Honduras',
  HUN: 'Hungría',
  IRN: 'Irán',
  IRQ: 'Irak',
  ITA: 'Italia',
  JAM: 'Jamaica',
  JOR: 'Jordania',
  JPN: 'Japón',
  KOR: 'Corea del Sur',
  KSA: 'Arabia Saudita',
  MAR: 'Marruecos',
  MEX: 'México',
  MLI: 'Malí',
  NED: 'Países Bajos',
  NGA: 'Nigeria',
  NOR: 'Noruega',
  NZL: 'Nueva Zelanda',
  PAN: 'Panamá',
  PAR: 'Paraguay',
  PER: 'Perú',
  POL: 'Polonia',
  POR: 'Portugal',
  QAT: 'Catar',
  RSA: 'Sudáfrica',
  SCO: 'Escocia',
  SEN: 'Senegal',
  SRB: 'Serbia',
  SUI: 'Suiza',
  SWE: 'Suecia',
  TUN: 'Túnez',
  TUR: 'Turquía',
  UKR: 'Ucrania',
  URU: 'Uruguay',
  USA: 'Estados Unidos',
  UZB: 'Uzbekistán',
  VEN: 'Venezuela',
  WAL: 'Gales',
}

function norm(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

const BY_ENGLISH: Record<string, string> = {
  algeria: 'Argelia',
  argentina: 'Argentina',
  australia: 'Australia',
  austria: 'Austria',
  belgium: 'Bélgica',
  'bosnia and herzegovina': 'Bosnia y Herzegovina',
  'bosnia herzegovina': 'Bosnia y Herzegovina',
  bolivia: 'Bolivia',
  brazil: 'Brasil',
  canada: 'Canadá',
  chile: 'Chile',
  'cote d ivoire': 'Costa de Marfil',
  'ivory coast': 'Costa de Marfil',
  cameroon: 'Camerún',
  'dr congo': 'Congo DR',
  'democratic republic of the congo': 'Congo DR',
  'congo dr': 'Congo DR',
  colombia: 'Colombia',
  'costa rica': 'Costa Rica',
  croatia: 'Croacia',
  'cape verde': 'Cabo Verde',
  'cabo verde': 'Cabo Verde',
  curacao: 'Curazao',
  curaçao: 'Curazao',
  czechia: 'Chequia',
  'czech republic': 'Chequia',
  denmark: 'Dinamarca',
  ecuador: 'Ecuador',
  egypt: 'Egipto',
  england: 'Inglaterra',
  spain: 'España',
  france: 'Francia',
  germany: 'Alemania',
  ghana: 'Ghana',
  greece: 'Grecia',
  haiti: 'Haiti',
  honduras: 'Honduras',
  hungary: 'Hungría',
  iran: 'Iran',
  iraq: 'Irak',
  italy: 'Italia',
  jamaica: 'Jamaica',
  jordan: 'Jordania',
  japan: 'Japón',
  'korea republic': 'Corea del Sur',
  'south korea': 'Corea del Sur',
  'saudi arabia': 'Arabia Saudita',
  morocco: 'Marruecos',
  mexico: 'México',
  mali: 'Mali',
  netherlands: 'Países Bajos',
  nigeria: 'Nigeria',
  norway: 'Noruega',
  'new zealand': 'Nueva Zelanda',
  panama: 'Panamá',
  paraguay: 'Paraguay',
  peru: 'Perú',
  poland: 'Polonia',
  portugal: 'Portugal',
  qatar: 'Catar',
  'south africa': 'Sudáfrica',
  scotland: 'Escocia',
  senegal: 'Senegal',
  serbia: 'Serbia',
  switzerland: 'Suiza',
  sweden: 'Suecia',
  tunisia: 'Túnez',
  turkey: 'Turquía',
  ukraine: 'Ucrania',
  uruguay: 'Uruguay',
  'united states': 'Estados Unidos',
  'united states of america': 'Estados Unidos',
  uzbekistan: 'Uzbekistan',
  venezuela: 'Venezuela',
  wales: 'Gales',
}

export function teamNameEs(code?: string | null, englishName?: string | null): string {
  const fifa = (code ?? '').trim().toUpperCase()
  if (fifa && BY_FIFA[fifa]) return BY_FIFA[fifa]

  const raw = (englishName ?? '').trim()
  if (!raw) return fifa || 'Equipo'

  const key = norm(raw)
  if (BY_ENGLISH[key]) return BY_ENGLISH[key]

  if (/[áéíóúñü]/i.test(raw)) return raw

  return raw
}
